spring.application.name=eazystore
debug=true
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %white(%logger{36}) - %msg%n
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
